// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckExtractor() {
  return window['go']['main']['App']['CheckExtractor']();
}

export function ScanFolder(arg1) {
  return window['go']['main']['App']['ScanFolder'](arg1);
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}

export function StartConversion(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartConversion'](arg1, arg2, arg3);
}
