// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {reforge} from '../models';
import {main} from '../models';

export function CancelConversion():Promise<void>;

export function CheckExtractor():Promise<boolean>;

export function GetSettings():Promise<reforge.Settings>;

export function SaveSettings(arg1:reforge.Settings):Promise<string>;

export function ScanFolder(arg1:string):Promise<main.ScanResult>;

export function SelectFolder():Promise<string>;

export function StartConversion(arg1:string,arg2:boolean,arg3:boolean):Promise<string>;
